apiVersion: v1
kind: Secret
metadata:
  name: sistemagdp-backend-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres.btdfjbmljwktngjelsco:sistema_Gdp_2005@aws-0-us-west-2.pooler.supabase.com:5432/postgres"
  JWT_SECRET: "miclavesupersegura123"