apiVersion: v1
kind: ConfigMap
metadata:
  name: sistemagdp-backend-config
data:
  PORT: "3006"
  IP: "0.0.0.0"
  FRONTEND: "http://sistemagdp-frontend-service:80"
  BACKEND: "http://sistemagdp-backend-service:3006"