apiVersion: v1
kind: Secret
metadata:
  name: sistemagdp-backend-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}