apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistemagdp-backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: sistemagdp-backend
  template:
    metadata:
      labels:
        app: sistemagdp-backend
    spec:
      containers:
        - name: sistemagdp-backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backendPort }}
          envFrom:
            - secretRef:
                name: sistemagdp-backend-secret
            - configMapRef:
                name: sistemagdp-backend-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"