apiVersion: v1
kind: Service
metadata:
  name: sistemagdp-frontend-service
spec:
  type: NodePort
  selector:
    app: sistemagdp-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007